-- AlterTable
ALTER TABLE "comments" ALTER COLUMN "note" SET DEFAULT 0,
ALTER COLUMN "note" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "movies" ALTER COLUMN "note" SET DEFAULT 0,
ALTER COLUMN "note" SET DATA TYPE DOUBLE PRECISION;
